
/*
    DO NOT MANUALLY EDIT THIS FILE.

    This file has been automaticaly generated by the anna bind
    utility. If you manually edit it, your changes will eventually be
    lost. Not to mention the fact that staring at machine generated
    code rots your brain. If this file is incorrect, either update the
    bind utility or update the binding source, which is located in the
    file:

    annaGame.bind

 */
#include "anna/config.h"

#include <stdlib.h>
#include <stdio.h>
#include <wchar.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
#include <pthread.h>

#include "screen.h"
#include "scene.h"
#include "render.h"
#include "GL/glew.h"
#include "GL/glu.h"
#include "SDL/SDL.h"
#include "linalg.h"

#include "anna/anna.h"

// Declare internal variables for all types defined in this module
anna_type_t *annaGame_scene_type;
anna_type_t *annaGame_transform_type;
anna_type_t *annaGame_vec_type;
anna_type_t *annaGame_ball_type_type;
anna_type_t *annaGame_ball_type;


// Data used to initialize all types defined in this module
const static anna_type_data_t anna_annaGame_type_data[] = 
{
};

// This is the source code of the various wrapper functions
const static anna_type_data_t anna_screen_type_data[] = 
{
};
const static anna_type_data_t anna_key_type_data[] = 
{
};

void anna_key_create(anna_stack_template_t *stack);
void anna_key_create(anna_stack_template_t *stack)
{
    anna_type_data_create(anna_key_type_data, stack);        
}
void anna_key_load(anna_stack_template_t *stack);
void anna_key_load(anna_stack_template_t *stack)
{
    mid_t latest_mid;    
    anna_function_t *latest_function;
    anna_type_t *stack_type = anna_stack_wrap(stack)->type;
    anna_module_data_t modules[] =
        {
        };
    anna_module_data_create(modules, stack);

    wchar_t *this_argn[] = {L"this"};

    anna_module_const_int(stack, L"escape", SDLK_ESCAPE, 0);
    anna_module_const_int(stack, L"left", SDLK_LEFT, 0);
    anna_module_const_int(stack, L"right", SDLK_RIGHT, 0);
    anna_module_const_int(stack, L"up", SDLK_UP, 0);
    anna_module_const_int(stack, L"down", SDLK_DOWN, 0);

    anna_type_data_register(anna_key_type_data, stack);
}

ANNA_VM_NATIVE(annaGame_i_screen_init, 3)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}

    // Mangle input parameters
    int native_param_width = anna_as_int(param[0]);
    int native_param_height = anna_as_int(param[1]);
    int native_param_fullscreen = anna_as_int(param[2]);

    // Validate parameters

    // Call the function
    screen_init(native_param_width, native_param_height, native_param_fullscreen);
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_screen_check_input, 0)
{
    // Validate parameters

    // Mangle input parameters

    // Validate parameters

    // Call the function
    screen_check_input();
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_screen_key_get, 1)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}

    // Mangle input parameters
    int native_param_key = anna_as_int(param[0]);

    // Validate parameters

    // Call the function
    int tmp_var_1 = screen_key_get(native_param_key);
    anna_entry_t *result = (tmp_var_1)?anna_from_int(1):null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_screen_destroy, 0)
{
    // Validate parameters

    // Mangle input parameters

    // Validate parameters

    // Call the function
    screen_destroy();
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_screen_swap_buffers, 0)
{
    // Validate parameters

    // Mangle input parameters

    // Validate parameters

    // Call the function
    screen_swap_buffers();
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

void anna_screen_create(anna_stack_template_t *stack);
void anna_screen_create(anna_stack_template_t *stack)
{
    anna_type_data_create(anna_screen_type_data, stack);        
}
void anna_screen_load(anna_stack_template_t *stack);
void anna_screen_load(anna_stack_template_t *stack)
{
    mid_t latest_mid;    
    anna_function_t *latest_function;
    anna_type_t *stack_type = anna_stack_wrap(stack)->type;
    anna_module_data_t modules[] =
        {
            { L"key", anna_key_create, anna_key_load},
        };
    anna_module_data_create(modules, stack);

    wchar_t *this_argn[] = {L"this"};


    anna_type_t *annaGame_i_screen_init_argv[] = {int_type, int_type, int_type};
    wchar_t *annaGame_i_screen_init_argn[] = {L"width", L"height", L"fullscreen"};
    latest_function = anna_module_function(stack, L"init", 0, &annaGame_i_screen_init, object_type, 3, annaGame_i_screen_init_argv, annaGame_i_screen_init_argn, 0, 0);

    anna_type_t *annaGame_i_screen_check_input_argv[] = {};
    wchar_t *annaGame_i_screen_check_input_argn[] = {};
    latest_function = anna_module_function(stack, L"checkInput", 0, &annaGame_i_screen_check_input, object_type, 0, annaGame_i_screen_check_input_argv, annaGame_i_screen_check_input_argn, 0, 0);

    anna_type_t *annaGame_i_screen_key_get_argv[] = {int_type};
    wchar_t *annaGame_i_screen_key_get_argn[] = {L"key"};
    latest_function = anna_module_function(stack, L"keyGet", 0, &annaGame_i_screen_key_get, object_type, 1, annaGame_i_screen_key_get_argv, annaGame_i_screen_key_get_argn, 0, 0);

    anna_type_t *annaGame_i_screen_destroy_argv[] = {};
    wchar_t *annaGame_i_screen_destroy_argn[] = {};
    latest_function = anna_module_function(stack, L"destroy", 0, &annaGame_i_screen_destroy, object_type, 0, annaGame_i_screen_destroy_argv, annaGame_i_screen_destroy_argn, 0, 0);

    anna_type_t *annaGame_i_screen_swap_buffers_argv[] = {};
    wchar_t *annaGame_i_screen_swap_buffers_argn[] = {};
    latest_function = anna_module_function(stack, L"swapBuffers", 0, &annaGame_i_screen_swap_buffers, object_type, 0, annaGame_i_screen_swap_buffers_argv, annaGame_i_screen_swap_buffers_argn, 0, 0);

    anna_type_data_register(anna_screen_type_data, stack);
}
const static anna_type_data_t anna_render_type_data[] = 
{
};

ANNA_VM_NATIVE(annaGame_i_render_init, 0)
{
    // Validate parameters

    // Mangle input parameters

    // Validate parameters

    // Call the function
    render_init();
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

void anna_render_create(anna_stack_template_t *stack);
void anna_render_create(anna_stack_template_t *stack)
{
    anna_type_data_create(anna_render_type_data, stack);        
}
void anna_render_load(anna_stack_template_t *stack);
void anna_render_load(anna_stack_template_t *stack)
{
    mid_t latest_mid;    
    anna_function_t *latest_function;
    anna_type_t *stack_type = anna_stack_wrap(stack)->type;
    anna_module_data_t modules[] =
        {
        };
    anna_module_data_create(modules, stack);

    wchar_t *this_argn[] = {L"this"};


    anna_type_t *annaGame_i_render_init_argv[] = {};
    wchar_t *annaGame_i_render_init_argn[] = {};
    latest_function = anna_module_function(stack, L"init", 0, &annaGame_i_render_init, object_type, 0, annaGame_i_render_init_argv, annaGame_i_render_init_argn, 0, 0);

    anna_type_data_register(anna_render_type_data, stack);
}
const static anna_type_data_t anna_scene_type_data[] = 
{
    { &annaGame_scene_type, L"Scene" },
};

ANNA_VM_NATIVE(annaGame_i_scene_scene_size_getter, 1)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->scene_size);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_time_getter, 1)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float(data->time);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_render_quality_getter, 1)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->render_quality);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_x_getter, 1)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->camera.pos[0]);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_x_setter, 2)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        float tmp = (float)anna_as_float(param[1]);

    data->camera.pos[0] = tmp;
    return param[1];
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_y_getter, 1)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->camera.pos[1]);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_y_setter, 2)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        float tmp = (float)anna_as_float(param[1]);

    data->camera.pos[1] = tmp;
    return param[1];
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_z_getter, 1)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->camera.pos[2]);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_z_setter, 2)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        float tmp = (float)anna_as_float(param[1]);

    data->camera.pos[2] = tmp;
    return param[1];
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_angle_getter, 1)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->camera.lr_rot);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_camera_angle_setter, 2)
{
    struct scene *data;
    data = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        float tmp = (float)anna_as_float(param[1]);

    data->camera.lr_rot = tmp;
    return param[1];
}

ANNA_VM_NATIVE(annaGame_i_scene_init, 3)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}

    // Mangle input parameters
    struct scene *native_param_this;
    native_param_this = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    char *native_param_name = (param[1] == null_entry) ? 0 : anna_string_payload_narrow(anna_as_obj(param[1]));
    int native_param_load = anna_as_int(param[2]);

    // Validate parameters

    // Call the function
    scene_init(native_param_this, native_param_name, native_param_load);
    anna_entry_t *result = null_entry;

    // Perform cleanup
    free(native_param_name);

    // Return result
    return param[0];
}

ANNA_VM_NATIVE(annaGame_i_scene_configure, 3)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}

    // Mangle input parameters
    struct scene *native_param_this;
    native_param_this = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    int native_param_tileLevels = anna_as_int(param[1]);
    float native_param_size = (float)anna_as_float(param[2]);

    // Validate parameters

    // Call the function
    scene_configure(native_param_this, native_param_tileLevels, native_param_size);
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_save_terrain, 1)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}

    // Mangle input parameters
    struct scene *native_param_this;
    native_param_this = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);

    // Validate parameters

    // Call the function
    scene_save_terrain(native_param_this);
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_render, 1)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}

    // Mangle input parameters
    struct scene *native_param_this;
    native_param_this = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);

    // Validate parameters

    // Call the function
    render(native_param_this);
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_update, 1)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}

    // Mangle input parameters
    struct scene *native_param_this;
    native_param_this = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);

    // Validate parameters

    // Call the function
    scene_update(native_param_this);
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_get_height, 3)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}

    // Mangle input parameters
    struct scene *native_param_this;
    native_param_this = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    float native_param_x = (float)anna_as_float(param[1]);
    float native_param_y = (float)anna_as_float(param[2]);

    // Validate parameters

    // Call the function
    float tmp_var_2 = scene_get_height(native_param_this, native_param_x, native_param_y);
    anna_entry_t *result = anna_from_float((double)tmp_var_2);

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_scene_get_slope, 4)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}
    if(param[3] == null_entry){return null_entry;}

    // Mangle input parameters
    struct scene *native_param_this;
    native_param_this = (struct scene *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    float native_param_x = (float)anna_as_float(param[1]);
    float native_param_y = (float)anna_as_float(param[2]);
    size_t native_param_slope_count = anna_list_get_count(anna_as_obj(param[3]));
    float* native_param_slope = malloc(sizeof(float) * native_param_slope_count);
    if(!native_param_slope){ return null_entry; }
    int native_param_slope_idx;
    for(native_param_slope_idx=0; native_param_slope_idx < native_param_slope_count; native_param_slope_idx++)
    {
        anna_entry_t *tmp = anna_list_get(anna_as_obj(param[3]), native_param_slope_idx);
        if(tmp == null_entry)
        {
            native_param_slope[native_param_slope_idx] = 0;
        }
        else
        {
                float native_param_slope_val = (float)anna_as_float(tmp);

            native_param_slope[native_param_slope_idx] = native_param_slope_val;
        }
    }

    // Validate parameters

    // Call the function
    scene_get_slope(native_param_this, native_param_x, native_param_y, native_param_slope);
    anna_entry_t *result = null_entry;

    // Perform cleanup
    for(native_param_slope_idx=0; native_param_slope_idx < native_param_slope_count; native_param_slope_idx++)
    {
            anna_entry_t *tmp = anna_from_float((double)native_param_slope[native_param_slope_idx]);

        anna_list_set(anna_as_obj(param[3]), native_param_slope_idx, tmp);
        
    }
    free(native_param_slope);

    // Return result
    return result;
}

void anna_scene_create(anna_stack_template_t *stack);
void anna_scene_create(anna_stack_template_t *stack)
{
    anna_type_data_create(anna_scene_type_data, stack);        
}
void anna_scene_load(anna_stack_template_t *stack);
void anna_scene_load(anna_stack_template_t *stack)
{
    mid_t latest_mid;    
    anna_function_t *latest_function;
    anna_type_t *stack_type = anna_stack_wrap(stack)->type;
    anna_module_data_t modules[] =
        {
        };
    anna_module_data_create(modules, stack);

    wchar_t *this_argn[] = {L"this"};


    anna_member_create_blob(annaGame_scene_type, ANNA_MID_CSTRUCT_PAYLOAD, 0, sizeof(struct scene));

    anna_member_create_native_property(
        annaGame_scene_type, anna_mid_get(L"sceneSize"),
        float_type, annaGame_i_scene_scene_size_getter, 0, 0);

    anna_member_create_native_property(
        annaGame_scene_type, anna_mid_get(L"time"),
        float_type, annaGame_i_scene_time_getter, 0, 0);

    anna_member_create_native_property(
        annaGame_scene_type, anna_mid_get(L"renderQuality"),
        float_type, annaGame_i_scene_render_quality_getter, 0, 0);

    anna_member_create_native_property(
        annaGame_scene_type, anna_mid_get(L"cameraX"),
        float_type, annaGame_i_scene_camera_x_getter, annaGame_i_scene_camera_x_setter, 0);

    anna_member_create_native_property(
        annaGame_scene_type, anna_mid_get(L"cameraY"),
        float_type, annaGame_i_scene_camera_y_getter, annaGame_i_scene_camera_y_setter, 0);

    anna_member_create_native_property(
        annaGame_scene_type, anna_mid_get(L"cameraZ"),
        float_type, annaGame_i_scene_camera_z_getter, annaGame_i_scene_camera_z_setter, 0);

    anna_member_create_native_property(
        annaGame_scene_type, anna_mid_get(L"cameraAngle"),
        float_type, annaGame_i_scene_camera_angle_getter, annaGame_i_scene_camera_angle_setter, 0);

    anna_type_t *annaGame_i_scene_init_argv[] = {annaGame_scene_type, string_type, int_type};
    wchar_t *annaGame_i_scene_init_argn[] = {L"this", L"name", L"load"};
    anna_member_create_native_method(
        annaGame_scene_type, anna_mid_get(L"__init__"), 0, 
        &annaGame_i_scene_init, object_type, 3, annaGame_i_scene_init_argv, annaGame_i_scene_init_argn, 0, 0);

    anna_type_t *annaGame_i_scene_configure_argv[] = {annaGame_scene_type, int_type, float_type};
    wchar_t *annaGame_i_scene_configure_argn[] = {L"this", L"tileLevels", L"size"};
    anna_member_create_native_method(
        annaGame_scene_type, anna_mid_get(L"configure"), 0, 
        &annaGame_i_scene_configure, object_type, 3, annaGame_i_scene_configure_argv, annaGame_i_scene_configure_argn, 0, 0);

    anna_type_t *annaGame_i_scene_save_terrain_argv[] = {annaGame_scene_type};
    wchar_t *annaGame_i_scene_save_terrain_argn[] = {L"this"};
    anna_member_create_native_method(
        annaGame_scene_type, anna_mid_get(L"saveTerrain"), 0, 
        &annaGame_i_scene_save_terrain, object_type, 1, annaGame_i_scene_save_terrain_argv, annaGame_i_scene_save_terrain_argn, 0, 0);

    anna_type_t *annaGame_i_scene_render_argv[] = {annaGame_scene_type};
    wchar_t *annaGame_i_scene_render_argn[] = {L"this"};
    anna_member_create_native_method(
        annaGame_scene_type, anna_mid_get(L"render"), 0, 
        &annaGame_i_scene_render, object_type, 1, annaGame_i_scene_render_argv, annaGame_i_scene_render_argn, 0, 0);

    anna_type_t *annaGame_i_scene_update_argv[] = {annaGame_scene_type};
    wchar_t *annaGame_i_scene_update_argn[] = {L"this"};
    anna_member_create_native_method(
        annaGame_scene_type, anna_mid_get(L"update"), 0, 
        &annaGame_i_scene_update, object_type, 1, annaGame_i_scene_update_argv, annaGame_i_scene_update_argn, 0, 0);

    anna_type_t *annaGame_i_scene_get_height_argv[] = {annaGame_scene_type, float_type, float_type};
    wchar_t *annaGame_i_scene_get_height_argn[] = {L"this", L"x", L"y"};
    anna_member_create_native_method(
        annaGame_scene_type, anna_mid_get(L"getHeight"), 0, 
        &annaGame_i_scene_get_height, float_type, 3, annaGame_i_scene_get_height_argv, annaGame_i_scene_get_height_argn, 0, 0);

    anna_type_t *annaGame_i_scene_get_slope_argv[] = {annaGame_scene_type, float_type, float_type, anna_list_type_get_mutable(float_type)};
    wchar_t *annaGame_i_scene_get_slope_argn[] = {L"this", L"x", L"y", L"slope"};
    anna_member_create_native_method(
        annaGame_scene_type, anna_mid_get(L"getSlope"), 0, 
        &annaGame_i_scene_get_slope, object_type, 4, annaGame_i_scene_get_slope_argv, annaGame_i_scene_get_slope_argn, 0, 0);

    anna_type_data_register(anna_scene_type_data, stack);
}
const static anna_type_data_t anna_primitives_type_data[] = 
{
    { &annaGame_transform_type, L"Transform" },
    { &annaGame_vec_type, L"Vec" },
    { &annaGame_ball_type_type, L"BallType" },
    { &annaGame_ball_type, L"Ball" },
};

ANNA_VM_NATIVE(annaGame_i_transform_init, 1)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}

    // Mangle input parameters
    struct transform *native_param_this;
    native_param_this = (struct transform *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);

    // Validate parameters

    // Call the function
    transform_init(native_param_this);
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return param[0];
}

ANNA_VM_NATIVE(annaGame_i_transform_identity, 1)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}

    // Mangle input parameters
    struct transform *native_param_this;
    native_param_this = (struct transform *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);

    // Validate parameters

    // Call the function
    transform_init(native_param_this);
    anna_entry_t *result = null_entry;

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_transform_get, 3)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}

    // Mangle input parameters
    struct transform *native_param_this;
    native_param_this = (struct transform *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    int native_param_idx1 = anna_as_int(param[1]);
    int native_param_idx2 = anna_as_int(param[2]);

    // Validate parameters

    // Call the function
    float tmp_var_3 = transform_get(native_param_this, native_param_idx1, native_param_idx2);
    anna_entry_t *result = anna_from_float((double)tmp_var_3);

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_transform_set, 4)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}
    if(param[3] == null_entry){return null_entry;}

    // Mangle input parameters
    struct transform *native_param_this;
    native_param_this = (struct transform *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    int native_param_idx1 = anna_as_int(param[1]);
    int native_param_idx2 = anna_as_int(param[2]);
    float native_param_value = (float)anna_as_float(param[3]);

    // Validate parameters

    // Call the function
    float tmp_var_4 = transform_set(native_param_this, native_param_idx1, native_param_idx2, native_param_value);
    anna_entry_t *result = anna_from_float((double)tmp_var_4);

    // Perform cleanup

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_vec_init, 1)
{
    struct vec *data;
    data = (struct vec *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    memset(data, 0, sizeof(struct vec));
    return param[0];
}

ANNA_VM_NATIVE(annaGame_i_ball_type_levels_getter, 1)
{
    struct ball_type *data;
    data = *(struct ball_type **)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_int(data->levels);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_type_alpha_getter, 1)
{
    struct ball_type *data;
    data = *(struct ball_type **)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_int(data->alpha);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_type_save, 3)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}
    if(param[2] == null_entry){return null_entry;}

    // Mangle input parameters
    struct ball_type *native_param_this;
    native_param_this = *(struct ball_type **)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    char *native_param_directory = (param[1] == null_entry) ? 0 : anna_string_payload_narrow(anna_as_obj(param[1]));
    char *native_param_name = (param[2] == null_entry) ? 0 : anna_string_payload_narrow(anna_as_obj(param[2]));

    // Validate parameters

    // Call the function
    ball_type_save(native_param_this, native_param_directory, native_param_name);
    anna_entry_t *result = null_entry;

    // Perform cleanup
    free(native_param_directory);
    free(native_param_name);

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_type_init, 1)
{
    struct ball_type *data;
    data = *(struct ball_type **)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    memset(data, 0, sizeof(struct ball_type));
    return param[0];
}

ANNA_VM_NATIVE(annaGame_i_primitives_ball_type_load, 2)
{
    // Validate parameters
    if(param[0] == null_entry){return null_entry;}
    if(param[1] == null_entry){return null_entry;}

    // Mangle input parameters
    char *native_param_directory = (param[0] == null_entry) ? 0 : anna_string_payload_narrow(anna_as_obj(param[0]));
    char *native_param_name = (param[1] == null_entry) ? 0 : anna_string_payload_narrow(anna_as_obj(param[1]));

    // Validate parameters

    // Call the function
    struct ball_type * tmp_var_5 = ball_type_load(native_param_directory, native_param_name);
anna_entry_t *result = anna_from_obj(anna_object_create(annaGame_ball_type_type));
    *((struct ball_type **)anna_entry_get_addr(anna_as_obj_fast(result), ANNA_MID_CSTRUCT_PAYLOAD)) = tmp_var_5;
    // Perform cleanup
    free(native_param_directory);
    free(native_param_name);

    // Return result
    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_scale_getter, 1)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->scale);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_scale_setter, 2)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        float tmp = (float)anna_as_float(param[1]);

    data->scale = tmp;
    return param[1];
}

ANNA_VM_NATIVE(annaGame_i_ball_ball_type_getter, 1)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    anna_entry_t *result = anna_from_obj(anna_object_create(annaGame_ball_type_type));
    *((struct ball_type **)anna_entry_get_addr(anna_as_obj_fast(result), ANNA_MID_CSTRUCT_PAYLOAD)) = data->type;
    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_radius_getter, 1)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_float((double)data->radius);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_radius_setter, 2)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        float tmp = (float)anna_as_float(param[1]);

    data->radius = tmp;
    return param[1];
}

ANNA_VM_NATIVE(annaGame_i_ball_visible_getter, 1)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        anna_entry_t *result = anna_from_int(data->visible);

    return result;
}

ANNA_VM_NATIVE(annaGame_i_ball_visible_setter, 2)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
        int tmp = anna_as_int(param[1]);

    data->visible = tmp;
    return param[1];
}

ANNA_VM_NATIVE(annaGame_i_ball_init, 1)
{
    struct ball *data;
    data = (struct ball *)anna_entry_get_addr(anna_as_obj_fast(param[0]), ANNA_MID_CSTRUCT_PAYLOAD);
    memset(data, 0, sizeof(struct ball));
    return param[0];
}

void anna_primitives_create(anna_stack_template_t *stack);
void anna_primitives_create(anna_stack_template_t *stack)
{
    anna_type_data_create(anna_primitives_type_data, stack);        
}
void anna_primitives_load(anna_stack_template_t *stack);
void anna_primitives_load(anna_stack_template_t *stack)
{
    mid_t latest_mid;    
    anna_function_t *latest_function;
    anna_type_t *stack_type = anna_stack_wrap(stack)->type;
    anna_module_data_t modules[] =
        {
        };
    anna_module_data_create(modules, stack);

    wchar_t *this_argn[] = {L"this"};


    anna_member_create_blob(annaGame_transform_type, ANNA_MID_CSTRUCT_PAYLOAD, 0, sizeof(struct transform));

    anna_type_t *annaGame_i_transform_init_argv[] = {annaGame_transform_type};
    wchar_t *annaGame_i_transform_init_argn[] = {L"this"};
    anna_member_create_native_method(
        annaGame_transform_type, anna_mid_get(L"__init__"), 0, 
        &annaGame_i_transform_init, object_type, 1, annaGame_i_transform_init_argv, annaGame_i_transform_init_argn, 0, 0);

    anna_type_t *annaGame_i_transform_identity_argv[] = {annaGame_transform_type};
    wchar_t *annaGame_i_transform_identity_argn[] = {L"this"};
    anna_member_create_native_method(
        annaGame_transform_type, anna_mid_get(L"identity"), 0, 
        &annaGame_i_transform_identity, object_type, 1, annaGame_i_transform_identity_argv, annaGame_i_transform_identity_argn, 0, 0);

    anna_type_t *annaGame_i_transform_get_argv[] = {annaGame_transform_type, int_type, int_type};
    wchar_t *annaGame_i_transform_get_argn[] = {L"this", L"idx1", L"idx2"};
    anna_member_create_native_method(
        annaGame_transform_type, anna_mid_get(L"__get__"), 0, 
        &annaGame_i_transform_get, float_type, 3, annaGame_i_transform_get_argv, annaGame_i_transform_get_argn, 0, 0);

    anna_type_t *annaGame_i_transform_set_argv[] = {annaGame_transform_type, int_type, int_type, float_type};
    wchar_t *annaGame_i_transform_set_argn[] = {L"this", L"idx1", L"idx2", L"value"};
    anna_member_create_native_method(
        annaGame_transform_type, anna_mid_get(L"__set__"), 0, 
        &annaGame_i_transform_set, float_type, 4, annaGame_i_transform_set_argv, annaGame_i_transform_set_argn, 0, 0);

    anna_member_create_blob(annaGame_vec_type, ANNA_MID_CSTRUCT_PAYLOAD, 0, sizeof(struct vec));
    anna_member_create_native_method(
	annaGame_vec_type, anna_mid_get(L"__init__"), 0,
	&annaGame_i_vec_init, object_type, 1, &annaGame_vec_type, this_argn, 0, 0);    

    anna_member_create_blob(annaGame_ball_type_type, ANNA_MID_CSTRUCT_PAYLOAD, 0, sizeof(struct ball_type *));

    anna_member_create_native_property(
        annaGame_ball_type_type, anna_mid_get(L"levels"),
        int_type, annaGame_i_ball_type_levels_getter, 0, 0);

    anna_member_create_native_property(
        annaGame_ball_type_type, anna_mid_get(L"alpha"),
        int_type, annaGame_i_ball_type_alpha_getter, 0, 0);

    anna_type_t *annaGame_i_ball_type_save_argv[] = {annaGame_ball_type_type, string_type, string_type};
    wchar_t *annaGame_i_ball_type_save_argn[] = {L"this", L"directory", L"name"};
    anna_member_create_native_method(
        annaGame_ball_type_type, anna_mid_get(L"save"), 0, 
        &annaGame_i_ball_type_save, object_type, 3, annaGame_i_ball_type_save_argv, annaGame_i_ball_type_save_argn, 0, 0);
    anna_member_create_native_method(
	annaGame_ball_type_type, anna_mid_get(L"__init__"), 0,
	&annaGame_i_ball_type_init, object_type, 1, &annaGame_ball_type_type, this_argn, 0, 0);    

    anna_type_t *annaGame_i_primitives_ball_type_load_argv[] = {string_type, string_type};
    wchar_t *annaGame_i_primitives_ball_type_load_argn[] = {L"directory", L"name"};
    latest_function = anna_module_function(stack, L"ballTypeLoad", 0, &annaGame_i_primitives_ball_type_load, annaGame_ball_type_type, 2, annaGame_i_primitives_ball_type_load_argv, annaGame_i_primitives_ball_type_load_argn, 0, 0);

    anna_member_create_blob(annaGame_ball_type, ANNA_MID_CSTRUCT_PAYLOAD, 0, sizeof(struct ball));

    anna_member_create_native_property(
        annaGame_ball_type, anna_mid_get(L"scale"),
        float_type, annaGame_i_ball_scale_getter, annaGame_i_ball_scale_setter, 0);

    anna_member_create_native_property(
        annaGame_ball_type, anna_mid_get(L"ballType"),
        annaGame_ball_type_type, annaGame_i_ball_ball_type_getter, 0, 0);

    anna_member_create_native_property(
        annaGame_ball_type, anna_mid_get(L"radius"),
        float_type, annaGame_i_ball_radius_getter, annaGame_i_ball_radius_setter, 0);

    anna_member_create_native_property(
        annaGame_ball_type, anna_mid_get(L"visible"),
        int_type, annaGame_i_ball_visible_getter, annaGame_i_ball_visible_setter, 0);
    anna_member_create_native_method(
	annaGame_ball_type, anna_mid_get(L"__init__"), 0,
	&annaGame_i_ball_init, object_type, 1, &annaGame_ball_type, this_argn, 0, 0);    

    anna_type_data_register(anna_primitives_type_data, stack);
}


// This function is called to create all types defined in this module

void anna_annaGame_create(anna_stack_template_t *stack);
void anna_annaGame_create(anna_stack_template_t *stack)
{
    anna_type_data_create(anna_annaGame_type_data, stack);        
}

// This function is called to load all functions and other declarations into the module

void anna_annaGame_load(anna_stack_template_t *stack);
void anna_annaGame_load(anna_stack_template_t *stack)
{
    mid_t latest_mid;    
    anna_function_t *latest_function;
    anna_type_t *stack_type = anna_stack_wrap(stack)->type;
    anna_module_data_t modules[] =
        {
            { L"screen", anna_screen_create, anna_screen_load},
            { L"render", anna_render_create, anna_render_load},
            { L"scene", anna_scene_create, anna_scene_load},
            { L"primitives", anna_primitives_create, anna_primitives_load},
        };
    anna_module_data_create(modules, stack);

    wchar_t *this_argn[] = {L"this"};


    anna_type_data_register(anna_annaGame_type_data, stack);
}

